# Generated by Django 5.2.5 on 2026-04-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Bike Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=0, max_digits=10)),
                ('terrain_type', models.CharField(choices=[('asphalt', 'Aspal'), ('offroad', 'Off-Road'), ('mixed', 'Mixed Terrain')], default='asphalt', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
                ('frame_material', models.CharField(default='Aluminium Alloy', max_length=100)),
                ('gear_system', models.CharField(blank=True, default='Shimano 21-Speed', max_length=100)),
                ('wheel_size', models.CharField(blank=True, default='700c', max_length=50)),
                ('total_units', models.PositiveIntegerField(default=1)),
                ('available_units', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('calories_per_km', models.DecimalField(decimal_places=1, default=40.0, help_text='Estimated calories burned per km', max_digits=5)),
                ('co2_saved_per_km', models.DecimalField(decimal_places=1, default=210.0, help_text='CO2 grams saved vs driving per km', max_digits=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bikecategory')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
