# Generated by Django 5.2.5 on 2026-04-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('duration_hours', models.PositiveIntegerField(choices=[(1, '1 Jam'), (2, '2 Jam'), (3, '3 Jam'), (4, '4 Jam'), (8, 'Setengah Hari (8 Jam)'), (24, 'Sehari Penuh (24 Jam)')])),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bikes.bike')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
